#-----------------------------#
#   ArmorStandEditor-Reborn   #
#-----------------------------#

#----------- LANGUAGE
#Name of the language file you wish to use

#NOTE: If you are editing en_US.yml, it will not persist across restarts due to it being overwritten
#Please read the comments at the top of that file before editing/changing/modifying.
lang: en_US.yml

#----------- WORLD SETTINGS
# Enable Per World Support for ArmorStandEditor - Not Enabling this
# means it will work for all worlds by default
enablePerWorldSupport: false

# Add in a list of Worlds where ArmorStandEditing is allowed to happen
# Please add your own worlds to this list. All Default Worlds are supported.
allowed-worlds:
  - world
  - world_nether
  - world_the_end

#----------- TOOL SETTINGS

#Name of the edit tool's item Material.
toolMaterial: minecraft:flint

#Whether edit tools should be managed solely by the plugin instead of the above material check.
#When enabled, only items created by the plugin will be usable to edit armor stands.
#The below settings will also be respected for further customising the item.
pluginManagedTool: false

#Item model to use for edit tool (requires pluginManagedItem: true)
toolItemModel: minecraft:flint

#Item name to add to edit tool (requires pluginManagedItem: true)
toolItemName: Example Name here

#Lore to add to edit tool (requires pluginManagedItem: true)
toolLore:
  - Example lore 1
  - Example lore 2

# Enable the below crafting recipe for the edit tool (requires pluginManagedItem: true)
toolAllowCrafting: false
toolRecipeShape:
  - '  #'
  - ' $ '
  - '   '
toolRecipeIngredients:
  '#': minecraft:iron_ingot
  $: minecraft:stick

#----------- ARMOR STAND SPECIFICS

#How many rotations to make a full circle in Coarse adjustment mode
coarse: 12

#How many rotations to make a full circle in Fine adjustment mode
fine: 120

# (NEW) Set a server limit on the Size of an ArmorStand
# NOte this has been changed to take into account the /attribute command version
minScaleValue: 0.1
maxScaleValue: 10

#------ GUI Options

#If true, the GUI will only open if the player is sneaking
requireSneaking: false

#Sends messages to the ActionBar
sendMessagesToActionBar: true

#------ Misc Options

#Debug Mode - For Development and Support Purposes ONLY!
# --- Do Not Enable. Will Generate ALOT OF NOISE in your Log Files
debugFlag: false
