name: ArmorStandEditor
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
version: 1.21.5-48.2
api-version: "1.21.5"
folia-supported: true
website: https://www.spigotmc.org/resources/94503/
authors: [Jim (AnEnragedPigeon) Wolfstorm, DreiFxn, Pinnkk, Kugge, Marfjeh, miknes123, rypofalem, sekwah41, Sikatsu1997, Cool_boy, sumdream, Amaury Carrade, nicuch, kotarobo, prettydude, Jumpy91, Niasio, Patbox, Puremin0rez, Prof-Bloodstone, PlanetTeamSpeak]
description: Allows players to edit data of armorstands without any commands.

dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    GriefPrevention:
      load: BEFORE
      required: false
      join-classpath: true
    PlotSquared:
      load: BEFORE
      required: false
      join-classpath: true
    CustomItems:
      load: AFTER
      required: false
      join-classpath: true

permissions:
  asedit.basic:
    description: Allow use of /asedit and basic edit modes.
  asedit.rename:
    description: Allow renaming armorstands
  asedit.equipment:
    description: Access armorstand equipment GUI
  asedit.disableSlots:
    description: Allows locking and unlocking the contents of an ArmorStand. When locked, armor and equipment can not be added or removed without unlocking it first.
  asedit.give:
    description: Allows use of /ase give
  asedit.reload:
    description: Allows Reloading of the ASE Config.
  asedit.movement:
    description: Changes whether the armor stand can be moved using the item for editing
  asedit.rotation:
    description: Allows player to rotate the ArmorStand
  asedit.copy:
    description: Allows the players to create copies of their ArmorStand Configurations.
  asedit.paste:
    description: Allows the players to apply of a copy of their ArmorStand Configuration.
  asedit.reset:
    description: Allows the reset of the ArmorStand back to Default values
  asedit.togglearmorstandvisibility:
    description: Toggles ArmorStand visibility.
  asedit.toggleitemframevisibility:
    description: Allows setting of ItemFrame Visibility
  asedit.toggleInvulnerability:
    description: Allows players to toggle the vulnerability state of an ArmorStand.
  asedit.togglebaseplate:
    description: Allows the toggling of the Baseplate of an ArmorStand.
  asedit.togglearms:
    description: Allows the toggling of the Arms of an ArmorStand.
  asedit.togglesize:
    description: Allows the toggling of the size of an ArmorStand.
  asedit.togglegravity:
    description: Changes whether the armor stand has gravity
  asedit.togglearmorstandglow:
    description: Allows toggling of the Glowing State of an ArmorStand.
  asedit.toggleitemframeglow:
    description: Allows toggling of the Glowing State of an ItemFrame.

  asedit.ignoreProtection.griefProtection:
    description: Allows user to ignore GriefProtection's Protection Limitations.
    default: false
  asedit.ignoreProtection.plotSquared:
    description: Allows user to ignore PlotSquared's Protection Limitations.
    default: false
  asedit.ignoreProtection.worldGuard:
    description: Allows user to ignore WorldGuard's Protection Limitations.
    default: false

  asedit.permpack.basic:
    default: true
    children:
      asedit.basic: true
      asedit.equipment: true
      asedit.togglegravity: true
      asedit.movement: true
      asedit.disableSlots: true
      asedit.rename: true
      asedit.rotation: true
      asedit.copy: true
      asedit.paste: true
      asedit.reset: true
      asedit.toggleInvulnerability: true
      asedit.togglebaseplate: true
      asedit.togglearms: true
      asedit.togglesize: true
      asedit.togglearmorstandvisibility: true
      asedit.toggleitemframevisibility: true
      asedit.togglearmorstandglow: true
      asedit.toggleitemframeglow: true

  asedit.permpack.admin:
    default: op
    children:
      asedit.ignorePermissions.*: true
      asedit.permpack.basic: true
      asedit.reload: true
      asedit.give: true
