[versions]
pluginYmlPaper = "0.8.0"
paperApi = "1.21.11-R0.1-SNAPSHOT"
griefPrevention = "18.0.0"
worldguard = "7.0.15"
customItems = "1.0-SNAPSHOT"
intellectualsitesBom = "1.55"
creativeItemFilter = "3.0-SNAPSHOT"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
griefPrevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref  = "griefPrevention" }
worldguard =  { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref  = "worldguard" }
customItems =  { group = "uk.co.notnull", name = "CustomItemsAPI", version.ref  = "customItems" }
plotsquaredCore = { group = "com.intellectualsites.plotsquared", name = "plotsquared-core" }
plotsquaredBukkit = { group = "com.intellectualsites.plotsquared", name = "plotsquared-bukkit" }
intellectualsitesBom = { group = "com.intellectualsites.bom", name = "bom-newest", version.ref = "intellectualsitesBom" }
creativeItemFilter = { group = "org.hurricanegames", name = "CreativeItemFilter", version.ref  = "creativeItemFilter" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }
